### ISSUE TITLE
React version? Or something compatible with react?

### ISSUE THREAD

**Issue by michaelGregoire** [internetarchive/iaux-icons#5]
It's awesome to see IA modernizing it's UI development. Would love to see the individual icons be provided in packages that are compatible with react in some way. At the very least for the internet archive logo. I have a react project that I'd like to use that to go along with links to pages on IA.

**Comment by shaneriley** [comment]
All of our web component development moving forward will be with LitElement, which uses LitHtml to render markup. You can still render the icons in a React app by way of LitHtml, which is [3.6KB gzipped](https://bundlephobia.com/result?p=lit-html@1.2.1). I made a quick example of the logo's use within a React app: https://codesandbox.io/s/sleepy-babbage-r5rgw

**Comment by michaelGregoire** [comment]
Oh, ok. So I just need a ref to it. Nice. That works. Thanks!

**Comment by michaelGregoire** [comment]
Well, thus far this doesn't work within the context of a next.js project. I get `Cannot use import statement outside a module`. I'm sure there might be some solution related to babel configuration, or something, but so far I haven't figured it out.
